# Generated by Django 3.2.4 on 2021-08-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='likecommunity',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='likecommunity',
            field=models.CharField(default='', max_length=200),
        ),
    ]
