# Generated by Django 3.2.4 on 2021-08-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account1', '0002_auto_20210811_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='coupon',
            field=models.CharField(default='', max_length=200),
        ),
    ]
