# Generated by Django 3.2.3 on 2021-07-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeowner_id', models.CharField(default='', max_length=200)),
                ('customer_id', models.CharField(default='', max_length=200)),
                ('customer_count', models.IntegerField(default=0)),
                ('customer_point', models.IntegerField(default=0)),
                ('storeowner_count', models.IntegerField(default=0)),
                ('storeowner_point', models.IntegerField(default=0)),
                ('certification_date', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(default='', max_length=200)),
                ('store_num', models.IntegerField(default=0)),
                ('storeowner_id', models.CharField(default='', max_length=200)),
                ('content', models.TextField(default='', max_length=200)),
                ('review_score', models.FloatField(default=0)),
                ('write_date', models.CharField(default='', max_length=200)),
                ('photo', models.CharField(default='', max_length=200)),
                ('review_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=200)),
                ('store_num', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('review_score', models.FloatField(default=0)),
                ('phonenumber', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('operationtime', models.CharField(default='', max_length=200)),
                ('menu', models.CharField(default='', max_length=200)),
                ('category', models.CharField(default='', max_length=200)),
                ('photo', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=200)),
                ('pick_count', models.IntegerField(default=0)),
                ('container_type', models.CharField(default='', max_length=200)),
                ('parking', models.CharField(default='', max_length=200)),
                ('storename', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
