# Generated by Django 3.2.3 on 2021-07-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210722_2347'),
        ('store', '0003_auto_20210724_2225'),
    ]

    operations = [
    ]
