# Generated by Django 3.2.4 on 2021-07-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_merge_0002_auto_20210722_2347_0003_auto_20210724_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_num',
            field=models.FloatField(default=0),
        ),
    ]
