# Generated by Django 3.2.4 on 2021-07-31 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_photo_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo_review',
        ),
    ]
