# Generated by Django 3.2.4 on 2021-07-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_photo_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo_review',
            old_name='store',
            new_name='review',
        ),
    ]
