# Generated by Django 3.2.4 on 2021-08-01 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210731_2256'),
        ('store', '0009_rename_store_photo_review_review'),
    ]

    operations = [
    ]
