# Generated by Django 3.1.7 on 2021-08-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_merge_20210801_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_review',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
