# Generated by Django 3.2.3 on 2021-07-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_productcompany_storeowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='coupon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='nickname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='phonenumber',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='sns',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='subdate',
            field=models.DateField(default='', verbose_name='가입일자'),
        ),
        migrations.AddField(
            model_name='productcompany',
            name='accountnumber',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='productcompany',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='productcompany',
            name='companyname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='productcompany',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='productcompany',
            name='operationtime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='productcompany',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='productcompany',
            name='phonenumber',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='productcompany',
            name='productcategory',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='nickname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='phonenumber',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='sns',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='subdate',
            field=models.DateField(default='', verbose_name='가입일자'),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='user_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='productcompany',
            name='user_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='user_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
