# Generated by Django 3.2.3 on 2021-07-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210702_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subdate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='subdate',
            field=models.CharField(default='', max_length=200),
        ),
    ]
