# Generated by Django 3.2.4 on 2021-08-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.CharField(default='', max_length=200)),
                ('subdate', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
